[project]
name = "adventjs"
version = "0.1.0"
description = "I l!kâ‚¬ cÃ˜mpliX!tyÌ¨Ì¸â–“â–’ Éª ðŸ§  Êžâ¨€ iÌ¶v!rÌ¸Ìƒâš âš¡ðŸ‘¾"
authors = [
    { name = "Juan Perdomo [Jakepy]", email = "perdomojuan187@gmail.com" }
]
dependencies = [
    "matplotlib>=3.9.3",
    "pyqt5>=5.15.11",
]
readme = "README.md"
requires-python = ">= 3.11"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
dev-dependencies = []

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/adventjs"]

[dependency-groups]
dev = [
    "ruff>=0.14.7",
]
